package dev.yjyoon.kwnotice.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFA8353E)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDAD9)
val light_onPrimaryContainer = Color(0xFF400009)
val light_secondary = Color(0xFF775656)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFDAD9)
val light_onSecondaryContainer = Color(0xFF2C1515)
val light_tertiary = Color(0xFF755A2F)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFDDAF)
val light_onTertiaryContainer = Color(0xFF281800)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201A1A)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201A1A)
val light_surfaceVariant = Color(0xFFF4DDDD)
val light_onSurfaceVariant = Color(0xFF524343)
val light_outline = Color(0xFF857372)
val light_inverseOnSurface = Color(0xFFFBEEED)
val light_inverseSurface = Color(0xFF362F2E)
val light_inversePrimary = Color(0xFFFFB3B3)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFFA8353E)

val dark_primary = Color(0xFFFFB3B3)
val dark_onPrimary = Color(0xFF680015)
val dark_primaryContainer = Color(0xFF881C29)
val dark_onPrimaryContainer = Color(0xFFFFDAD9)
val dark_secondary = Color(0xFFE6BDBC)
val dark_onSecondary = Color(0xFF442929)
val dark_secondaryContainer = Color(0xFF5D3F3F)
val dark_onSecondaryContainer = Color(0xFFFFDAD9)
val dark_tertiary = Color(0xFFE5C18D)
val dark_onTertiary = Color(0xFF422C05)
val dark_tertiaryContainer = Color(0xFF5B421A)
val dark_onTertiaryContainer = Color(0xFFFFDDAF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201A1A)
val dark_onBackground = Color(0xFFECE0DF)
val dark_surface = Color(0xFF201A1A)
val dark_onSurface = Color(0xFFECE0DF)
val dark_surfaceVariant = Color(0xFF524343)
val dark_onSurfaceVariant = Color(0xFFD7C1C1)
val dark_outline = Color(0xFFA08C8C)
val dark_inverseOnSurface = Color(0xFF201A1A)
val dark_inverseSurface = Color(0xFFECE0DF)
val dark_inversePrimary = Color(0xFFA8353E)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB3B3)

val seed = Color(0xFF962732)
